export default {
   uz: {
      online: 'tarmoqda',
      plasholder: 'Qidiruv',
      onl: 'a\'zolar',
      inp: 'Xabar yozing',
      alt: 'Rasm kelmadi boshqattan rinib korin',
      tahrir: 'Tahrirlash uchun rasm ustiga sichqonchaning chap tugmasini bosing',
      check: 'Tasvirni siqish',
      sar: 'Sarlavha',
      add: 'Qo\'shish',
      cancel: 'Bekor qilish',
      send: 'Yuborish',
   },
   ru: {
      online: 'в сети',
      plasholder: 'Поиск',
      onl: 'yчастников',
      inp: 'Напиши сообщение',
      alt: 'Картинка больше не пришлa',
      tahrir: 'щелкните левой кнопкой мыши на фото для редактирования',
      check: 'Сжать изображение',
      sar: 'Подпись',
      add: 'Добавлять',
      cancel: 'Отмена',
      send: 'Отправлять',
   },
   en: {
      online: 'online',
      plasholder: 'Search',
      onl: 'members',
      inp: 'Write a message',
      alt: 'The picture did not come again',
      tahrir: 'left-click on the photo to edit',
      check: 'Compress image',
      sar: 'Caption',
      add: 'Add',
      cancel: 'Cancel',
      send: 'Send',
   },
}